blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/orgs/BEST-Kosice/discussions
    about: "PoloÅ¾te otÃ¡zku alebo sa s nami podelte o svoj nÃ¡pad na GitHub alebo na Discord v kanÃ¡li #it-wg."
  - name: ğŸ“ Contributing
    url: https://github.com/BEST-Kosice/.github?tab=contributing-ov-file#
    about: "Pred otvorenÃ­m novÃ©ho issue sa uistite, Å¾e ste si pozorne preÄÃ­tali CONTRIBUTING.md."